### ISSUE TITLE
Add support for fire & forget voice message

### ISSUE THREAD

**Issue by matt-manywho** [manywho/service-twilio#13]
It would be great if there was an action that allowed you to send a message as text (with options to select the voice & language) that would be "read" to a target number

**Comment by josecollazzi** [comment]
the link to the ticket in the commit: 
````#13 try to fetch from database with a delay if the request for a sms````

is wrong should be for issue #16, I will keep the commit message just to not break the history.

**Comment by josecollazzi** [comment]
I have reviewed the code and I made some changes
