### ISSUE TITLE
Sometimes redis doesn't find some entries and make the service fail

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-twilio#16]
This seems to happen because the callback is done before some data is saved in Redis, and the second call is faster that the first one.

E.g. 
action send SMS
1) send SMS POST /api/twilio/2/messages/smssimple
2) /api/twilio/2/callback/status/message (with MessageStatus sent) return 500
{"kind":"service","uri":"/api/twilio/2/callback/status/message","statusCode":500,"responseBody":null,"responseHeaders":null,"message":"Could not find a stored request for the message with SID or From number: SMyyyxxxxwww48a32decxxxxxxd3","invokeType":null,"action":null}

But at the end of the flow the message request for MessageSid SMyyyxxxxwww48a32decxxxxxxd3 exist in database. When I execute the flow the second time most of the time works (probably because cache makes the first call faster).

**Comment by josecollazzi** [comment]
@jonjomckay  ready for review ⭕️

**Comment by josecollazzi** [comment]
The commit for this issue is in https://github.com/manywho/service-twilio/commit/82df1878abcedea43a910397e376d80609efb96c

**Comment by jonjomckay** [comment]
@josecollazzi I just left a comment on that commit for you :)

**Comment by josecollazzi** [comment]
thank you @jonjomckay 
Could you please take a look at the changes?

**Comment by jonjomckay** [comment]
💯
