### ISSUE TITLE
Mistake in the urls /callback/callbackTwiml

### ISSUE THREAD

**Issue by josecollazzi** [manywho/service-twilio#17]
The base URL for the resources /callback/callbackTwiml should be /callback/twiml, but this mistake have been in prod, it is better if we keep the compatibility for some time before the deprecation.

**Comment by josecollazzi** [comment]
@jonjomckay  could you please review?

**Comment by jonjomckay** [comment]
@josecollazzi it looks good functionally, but could you add a `@deprecated` JavaDoc to the class including a `@use` to point people to the class reference? Like this: https://github.com/manywho/sdk-java/blob/608acef2a5bbc7f1b13f24e85679058fc8658063/sdk-core/src/main/java/com/manywho/sdk/entities/run/elements/type/ListFilterWhere.java#L9

**Comment by josecollazzi** [comment]
cool comment added 🔑
