### ISSUE TITLE
Twilio service Sms limitation to 160 characters

### ISSUE THREAD

**Issue by jose-manywho** [manywho/service-twilio#3]
When we send a Sms it restricts the body to 160 characters which isn't a lot with our URLs!

The problem is that we are using
'getSmsFactory()'
instead of
`getMessageFactory()`

When we use getMessageFactory() the library will split body in the needed messages, and that will fix the problem.

More info about concatenated sms:
https://www.twilio.com/help/faq/sms/does-twilio-support-concatenated-sms-messages-or-messages-over-160-characters

I will do a pull request about this issue

**Comment by jonjo-manywho** [comment]
Merged :shipit:
